### ISSUE TITLE
License in README disagrees with license in LICENSE file

### ISSUE THREAD

**Issue by ssokolow** [sudleyplace/DPMIONE#2]
The license text in `README.TXT` is as follows:

> This program may be used free for non-commercial use; commercial use
requires a volume purchase agreement from the author.  It may be
freely distributed as long as no part of the program or its
documentation is altered and the program and its documentation are
kept together.

...but the `LICENSE` file and the [website](http://www.sudleyplace.com/dpmione/) say that DPMIONE is licensed under the GNU GPL v3. Given that it's two against one, I'm guessing this is a case of forgetting to update `README.txt` to match `LICENSE.TXT`.

...not that I'm overly worried right now, given the following passages in the GNU GPL v3 (emphasis mine):

>  Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>
 Everyone is permitted to copy and distribute verbatim copies
 of this license document, **but changing it is not allowed.**

>   All other non-permissive additional terms are considered "further
restrictions" within the meaning of section 10.  **If the Program as you
received it, or any part of it, contains a notice stating that it is
governed by this License along with a term that is a further
restriction, you may remove that term.**  If a license document contains
a further restriction but permits relicensing or conveying under this
License, you may add to a covered work material governed by the terms
of that license document, provided that the further restriction does
not survive such relicensing or conveying.

(TL;DR: The GPL3 allows recipients to ignore "commercial use
requires a volume purchase agreement from the author" and it's copyright infringement to remove that clause from the text of the GPL3. I believe the FSF also registered GNU GPL as a trademark that's only licensed to you for use with their un-modified text of GPL-family licenses to be absolutely sure their intent was preserved.)

**Comment by sudleyplace** [comment]
Thanks for the sharp eyes.  I've corrected the text in the README file.  Thanks again.

**Comment by ssokolow** [comment]
No problem. It's the least I can do.
