### ISSUE TITLE
Could not download dpmione.zip, FTP server requires authentication

### ISSUE THREAD

**Issue by SzieberthAdam** [sudleyplace/DPMIONE#4]
As title sais.

**Comment by sudleyplace** [comment]
On 9/1/2021 5:27 PM, Szieberth Ádám wrote:
> As title sais.

Some time ago when I moved my website to a new server, I found to my 
dismay that the new server didn't support FTP connections.

Try http://sudleyplace.com/dpmione/dpmione.zip.

I found a link pointing to my old FTP site in the text for 
http://www.sudleyplace.com/dpmione/ as well as in README.TXT both of 
which I have changed to point to the above link.  If you clicked on a 
different link, please let me know and I'll change that one, too.

Thanks for bringing this to my attention.

-- 
_______________________________________________________________
Bob Smith - ***@***.***
http://www.sudleyplace.com - http://www.nars2000.org
